### ISSUE TITLE
Support dynamic views

### ISSUE THREAD

**Issue by ribizli** [ngneat/from-event#4]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

`@ViewChild`'s setter is called several times, if the element is toggled in the view. If the element is removed (e.g. through `*ngIf=show`), the setter is called with `undefined` `ElementRef`. This case is not handled (NPE).

If we swap the element with an other (e.g. `ngIf` + `else` with same `#templateVar`), the setter is called again with the other `ElementRef`. (1) The former `fromEvent` is not unsubscribed (might not cause memory leak), and (2) the chaining also breaks, since `fromEvent` is not usable as event target (aka in `subscribe`).

## Expected behavior

To keep the original `Subject` for the users and swap out it's source with the latest `ElementRef`'s events.

Also verify if unsubscribe from the previous `ElementRef`'s events is needed.

## Minimal reproduction of the problem with instructions

https://ng-run.com/edit/VqWigxZwytu3Sj26PDnK

1. click on 'test' and see the alert
2. click on 'toggle' to swap out the button first
3. click on 'test alternative' and see that alert is not triggered anymore
4. click on 'toggle' to remove the button, see the NPE

## What is the motivation / use case for changing the behavior?

Free this lib from bugs ;)

## Environment

<pre><code>
Angular version: 9.1.1

Browser:
- [X] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
</code></pre>

**Comment by NetanelBasal** [comment]
@tonivj5 could you take it, please?

**Comment by ribizli** [comment]
@tonivj5 if you want I could take over, but you must feel more comfortable with your change.

**Comment by tonivj5** [comment]
Good catch @ribizli 

I'll fix it :+1:

**Comment by NetanelBasal** [comment]
We have an issue:

> error TS1169: A computed property name in an interface must refer to an expression whose type is a literal type or a 'unique symbol' type.

**Comment by tonivj5** [comment]
At build?

**Comment by NetanelBasal** [comment]
Yes, I added the build to the CI process.

**Comment by tonivj5** [comment]
Ok, I will check it :+1:

**Comment by ribizli** [comment]
@tonivj5 I'm not sure, about the code in `finalize()`, where the subject gets completed (`event$.complete()`). Can you please explain it for me? Doesn't it cause late subscribers won't get notified anymore?

**Comment by ribizli** [comment]
@tonivj5 also (IMHO) using a `Subject` as source is not really safe after operations piped on it... (I've got TS complaining about)

See my plain test for my `.complete()` concern: https://stackblitz.com/edit/rxjs-dlybi3?file=index.ts

**Comment by tonivj5** [comment]
> Can you please explain it for me? 

Sure!

> Doesn't it cause late subscribers won't get notified anymore?

No, it will create a new `Subject` and subscription to the event with the new subscription. It works because we return a [`defer`](https://github.com/ngneat/from-event/blob/master/projects/ngneat/from-event/src/lib/from-event.ts#L30) observable, on subscribe, it will [create the `Subject`](https://github.com/ngneat/from-event/blob/90a53b9466887974da182cb06ca128f5179f5d5a/projects/ngneat/from-event/src/lib/helpers.ts#L19) (if it's needed) and [subscribe to the event](https://github.com/ngneat/from-event/blob/90a53b9466887974da182cb06ca128f5179f5d5a/projects/ngneat/from-event/src/lib/helpers.ts#L41) (if it's possible). [Defer docs](https://rxjs.dev/api/index/function/defer).

`Defer` allow us to run `initIfNeeded` and `subscribeToEventIfPossible` on every subscription. And `finalize` release the memory (complete the the subject and unsubscribe from `fromEvent`) when no one is subscribed to it.

**Comment by tonivj5** [comment]
> also (IMHO) using a Subject as source is not really safe after operations piped on it... (I've got TS complaining about)

However, type says that `pipe` returns an `Observable`, it's returning itself (a `Subject`), that's the reason because [we cast it](https://github.com/ngneat/from-event/blob/master/projects/ngneat/from-event/src/lib/helpers.ts#L37).

Yeah, we could have an `source` symbol (subject piped) and our `subject` symbol (without piped), or in our `defer` returns `this[tokens.subject].asObservable()` to limit how it can be used. But I think it doesn't improve it too much.

> See my plain test for my .complete() concern: stackblitz.com/edit/rxjs-dlybi3?file=index.ts

This example doesn't show the same behavior that we are really doing. Here I have modified your example to reflect more properly how `FromEvent` is working: https://stackblitz.com/edit/rxjs-eacmif?file=index.ts

**Comment by ribizli** [comment]
I see you point, but I really believe it is over-complicated. Having a `Subject` and the `finalize` logic for unsubscribing the `fromEvent` is IMHO sufficient. The `defer` and `share` stuff is just complication.

**Comment by tonivj5** [comment]
Surely it can be improved! You can play with the code and check if tests pass (I think it covers a lot of use-cases :sweat_smile:)

A few notes if we remove `defer` or `share` (it could lead to more problems...):

- Without `defer`, the subject or subscription wouldn't be created on demand, for example, this POC would fail
```ts
constructor() {
	const logSomething$ = this.button$/* getter */.pipe(tap(console.log));
	// called finalize (subject removed and unsubscribe from event)
	logSomething$.subscribe().unsubscribe();

	// point to a completed/dead subject, it completes automatically
	logSomething/* no getter */.subscribe()
}
```

- Without `share`, if one subject is unsubscribed, `finally` is called and clean up is done and this would affect to other subscriptions to the same subject, for example, this POC would fail

```ts
constructor() {
	this.button$.subscribe();
	// it calls finalize and this subscription and the above one complete
	this.button$.subscribe().unsubscribe();
}
```

**Comment by NetanelBasal** [comment]
@tonivj5 You did a great job!

**Comment by ribizli** [comment]
yes, you are right, I reviewed my comment and deleted. `share` is
definitely needed. The `defer` is a minor memory optimisation. Without
defer you shouldn't complete and discard the subject and the POC works.

I like your current solution, don't change anything. 😉
